---
#will do an apt-get update/upgrade and reboot the device

- name: update and upgrade apt packages
  apt:
    upgrade=yes
    update_cache=yes

- name: restart machine
  command: shutdown -r now "Ansible reboot triggered"
  async: 0
  poll: 0
  ignore_errors: true